name: local_store_management
description: Gestionale desktop offline per negozio, riscritto in Flutter.
publish_to: none
version: 0.1.6-b5

environment:
  sdk: '>=3.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  barcode: ^2.2.9
  barcode_widget: ^2.0.4
  excel: ^4.0.6
  file_selector: ^1.1.0
  image: 4.3.0
  path: ^1.9.1
  path_provider: ^2.1.6
  pdf: 3.12.0
  printing: 5.14.3
  sqlite3: ^3.5.0
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/app-icon.base64
